post_install() {
  getent group tshock >/dev/null 2>&1 || groupadd tshock 
  getent passwd tshock >/dev/null 2>&1 || useradd -g tshock -d /opt/tshock/ -s /bin/bash tshock
  chown -R tshock:tshock opt/tshock/ var/log/tshock
}

post_upgrade() {
  post_install $1
}

post_remove() {
  if getent passwd tshock >/dev/null 2>&1; then
    userdel tshock 
  fi
  if getent group tshock >/dev/null 2>&1; then
    groupdel tshock 
  fi
}

